/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nweje_biometric;

import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static nweje_biometric.pc_work_page.jLabel3;
import static nweje_biometric.pc_work_page.photo;

/**
 *
 * @author Chinwendu Nweje
 */
public class hod_work_page extends javax.swing.JFrame {

    /**
     * Creates new form hod_work_page
     */
    String course_name = null;
    String course_code = null;
    static String dept = null;
    String lect_lname = null;
    String staff_id = null;
    String allocate_id = null;

    String lect_id = null;
    int lect_id_index = 0;

    static String course_code_list[] = {
        "CSC 101",
        "CSC 205",
        "CHM 101",
        "CHM 107",
        "MTH 101",
        "MTH 103",
        "PHY 101",
        "PHY 107",
        "EEE 301",
        "EEE 303",
        "EEE 305",
        "EEE 307",
        "EEE 309",
        "EEE 320",
        "MEE 307",
        "MEE 309",
        "MEE 313",
        "MEE 315",
        "MEE 331",};

    static String[] comp_sci_id_list = {
        "1000",
        "1001",
        "1002",
        "1003",
        "1004",
        "1005",
        "1006",
        "1007",};

    static String[] mech_eng_id_list = {
        "2000",
        "2001",
        "2002",
        "2003",
        "2004",
        "2005",
        "2006",};

    static String[] elect_eng_id_list = {
        "3000",
        "3001",
        "3002",
        "3003",
        "3004",};

    static String[] basic_sci_id_list = {
        "4000",
        "4001",
        "4002",
        "4003",
        "4004",
        "4005",
        "4006",
        "4007",
        "4008",};

    public hod_work_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View Attendance", jPanel2);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel17.setText("Course List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel17)))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New Allocate", jPanel3);

        jLabel1.setText("Allocate Courses to Lecturers");

        jLabel2.setText("Course Name");

        jLabel3.setText("Course Code");

        jLabel4.setText("Department");

        jLabel5.setText("Lecturer's Name");

        jLabel6.setText("Staff ID");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel10.setText("Allocate ID");

        jButton1.setText("Allocate Lecturer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(164, 164, 164))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(69, 69, 69)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Allocate Lecturers", jPanel1);

        jLabel11.setText("Name");

        jLabel12.setText("Staff ID");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        jLabel15.setText("Department");

        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel15)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //food_item = jList1.getSelectedValue();
            course_name = jList1.getSelectedValue();
            course_code = jLabel7.getText();
            dept = jLabel8.getText();
            lect_lname = jComboBox2.getSelectedItem().toString();
            staff_id = jLabel9.getText();
            allocate_id = jTextField1.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biometric_attendance_schema", "root", "password");
            PreparedStatement ps = con.prepareStatement("insert into lecturer_allocation values (?,?,?,?,?,?)");



            ps.setString(1, allocate_id);
            ps.setString(2, course_name);
            ps.setString(3, course_code);
            ps.setString(4, dept);
            ps.setString(5, lect_lname);
            ps.setString(6, staff_id);

            int rs = ps.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, lect_lname + " has been allocated course: " +course_name + """
                                                           with allocation ID of: """ + allocate_id);
            
            

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Allocation Error");
            System.err.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        jLabel9.setText(null);

        if ((jLabel8.getText()).contains("Basic Science")) {
            int basic_sci_id_index = jComboBox2.getSelectedIndex();
            String basic_sci_id = basic_sci_id_list[basic_sci_id_index];
            jLabel9.setText(basic_sci_id);

        } else if ((jLabel8.getText()).contains("Computer Science")) {
            int comp_sci_id_index = jComboBox2.getSelectedIndex();
            String comp_sci_id = comp_sci_id_list[comp_sci_id_index];
            jLabel9.setText(comp_sci_id);

        } else if ((jLabel8.getText()).contains("Mechanical Eng")) {
            int mech_eng_id_index = jComboBox2.getSelectedIndex();
            String mech_eng_id = mech_eng_id_list[mech_eng_id_index];
            jLabel9.setText(mech_eng_id);

        } else {
            int elect_eng_id_index = jComboBox2.getSelectedIndex();
            String elect_eng_id = elect_eng_id_list[elect_eng_id_index];
            jLabel9.setText(elect_eng_id);
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
//        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_form","root","password");
//            PreparedStatement ps = con.prepareStatement("select * from course_list where name=? ");
//            
//                    ps.setString(1, name );
//                    ResultSet rs = ps.executeQuery();
//                    while(rs.next()){
//                        jTextField6.setText(rs.getString(1));
//                        jTextField7.setText(rs.getString(2));
//                        jTextField8.setText(rs.getString(3));
//                        jTextField9.setText(rs.getString(4));
//                        
//                        dept = rs.getString(5);
//                        int count = jComboBox2.getItemCount();
//                        for(int i=0; i<count; i++){
//                            if(dept.equalsIgnoreCase(jComboBox2.getItemAt(i).toString())){
//                                jComboBox2.setSelectedIndex(i);
//                                break;
//                            }
//                        }
//                                
//                         Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) rs.getString(7));
//                         jDateChooser2.setDate(date);
//                                
//                        sex = rs.getString(6);
//                        if (sex.equalsIgnoreCase("Male")){
//                            jRadioButton3.setSelected(true);}
//                        if (sex.equalsIgnoreCase("Female")){
//                            jRadioButton4.setSelected(true);}
//                        
//                    }
//                    con.close();
//        }
//        catch(Exception e){
//            System.out.println(e);
//        }







//        int course_code_index = jList1.getSelectedIndex();
//        course_code = course_code_list[course_code_index];
//        jLabel7.setText(course_code);
//
//        if (course_code.contains("MEE")) {
//            dept = "Mechanical Eng";
//            jLabel8.setText(dept);
//
//            jComboBox2.removeAllItems();
//            //jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Dr. Nobert Edomah");
//            jComboBox2.addItem("Mr. Rilwan Balogun");
//            jComboBox2.addItem("Dr. Bamidele Jerimiah ");
//            jComboBox2.addItem("Dr. Adekunle Oyelami ");
//            jComboBox2.addItem("Prof Roland Loto");
//        } else if (course_code.contains("EEE")) {
//            dept = "Electrical Eng";
//            jLabel8.setText(dept);
//
//            jComboBox2.removeAllItems();
//            //jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Dr. Nobert Edomah");
//            jComboBox2.addItem("Mr. Rilwan Balogun");
//            jComboBox2.addItem("Dr. Bamidele Jerimiah ");
//            jComboBox2.addItem("Dr. Adekunle Oyelami ");
//            jComboBox2.addItem("Prof Roland Loto");
//
//        } else if (course_code.contains("CSC")) {
//            dept = "Computer Science";
//            jLabel8.setText(dept);
//
//            jComboBox2.removeAllItems();
//            //jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Professor Kingsley Ukoaha");
//            jComboBox2.addItem("Dr. Pius Onobhayedo");
//            jComboBox2.addItem("Dr. Desmond Moru");
//            jComboBox2.addItem("Dr. Kazeem Oyebode");
//            jComboBox2.addItem("Dr. Edward Ofoegbu ");
//            jComboBox2.addItem("Mr. Moses Bello");
//            jComboBox2.addItem("Mr. Taiwo Amoo");
//            jComboBox2.addItem("Mr. Charles Igah");
//        } else {
//            dept = "Basic Science";
//            jLabel8.setText(dept);
//
//            jComboBox2.removeAllItems();
//            //jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Dr. Edith Ofor");
//            jComboBox2.addItem("Miss Grace Okoacha");
//            jComboBox2.addItem("Dr. Eno Akarawak");
//            jComboBox2.addItem("Dr. Clinton Ifegwu");
//            jComboBox2.addItem("Mr. Akintunde Oludayo");
//            jComboBox2.addItem("Miss Akudo Ijezie");
//            jComboBox2.addItem("Dr Patrick Osatohamwen");
//            jComboBox2.addItem("Dr. Julius Ehijie");
//            jComboBox2.addItem("Dr. Ozuma Oduah");
//        }

//        if (jLabel8.getText().contains("Basic Science")) {
//            jComboBox2.removeAllItems();
//            jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Dr. Edith Ofor");
//            jComboBox2.addItem("Miss Grace Okoacha");
//            jComboBox2.addItem("Dr. Eno Akarawak");
//            jComboBox2.addItem("Dr. Clinton Ifegwu");
//            jComboBox2.addItem("Mr. Akintunde Oludayo");
//            jComboBox2.addItem("Miss Akudo Ijezie");
//            jComboBox2.addItem("Dr Patrick Osatohamwen");
//            jComboBox2.addItem("Dr. Julius Ehijie");
//            jComboBox2.addItem("Dr. Ozuma Oduah");
//
//        } else if (course_code.contains("CSC")) {
//            jComboBox2.removeAllItems();
//            jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Professor Kingsley Ukoaha");
//            jComboBox2.addItem("Dr. Pius Onobhayedo");
//            jComboBox2.addItem("Dr. Desmond Moru");
//            jComboBox2.addItem("Dr. Kazeem Oyebode");
//            jComboBox2.addItem("Dr. Edward Ofoegbu ");
//            jComboBox2.addItem("Mr. Moses Bello");
//            jComboBox2.addItem("Mr. Taiwo Amoo");
//            jComboBox2.addItem("Mr. Charles Igah");
//
//        } else if (jLabel8.getText().contains("Mechanical Eng")) {
//            jComboBox2.removeAllItems();
//            jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Professor Bolu Christian");
//            jComboBox2.addItem("Professor Benjamin Anyaegbuna");
//            jComboBox2.addItem("Dr. Darlington Agholor ");
//            jComboBox2.addItem("Capt. Stan Igwe ");
//            jComboBox2.addItem("Engr. Paul Onoriode");
//            jComboBox2.addItem("Prof Joseph Ajiboye ");
//            jComboBox2.addItem("Dr.George Ihenacho");
//
//        } else {
//            jComboBox2.removeAllItems();
//            jComboBox2.setSelectedItem(null);
//            jComboBox2.addItem("Dr. Nobert Edomah");
//            jComboBox2.addItem("Mr. Rilwan Balogun");
//            jComboBox2.addItem("Dr. Bamidele Jerimiah ");
//            jComboBox2.addItem("Dr. Adekunle Oyelami ");
//            jComboBox2.addItem("Prof Roland Loto");
//        }
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hod_work_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hod_work_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hod_work_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hod_work_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hod_work_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
